### ISSUE TITLE
test the model on my own dataset

### ISSUE THREAD

**Issue by fatemechangizian** [dvlab-research/SphereFormer#10]
Hello,
First, congrats on the great work.
I would really appreciate it if you could guide me on how can I use the pre-trained weights to test the model on my own dataset.
Thank you in advance for your help and feedback!

Best,

**Comment by X-Lai** [comment]
I suggest that you rewrite a dataset script following `util/nuscenes.py` or other datasets. Then modify the `train.py` accordingly (such as the `val_data` variable).
