### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by pomeloooo** [dvlab-research/SphereFormer#11]
bachsize=4 still report that

**Comment by X-Lai** [comment]
Which dataset?

**Comment by pomeloooo** [comment]
The dataset is semantic kitti&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Xin Lai ***@***.***&gt;
Date: Wed,Apr 12,2023 11:08 PM
To: dvlab-research/SphereFormer ***@***.***&gt;
Cc: pomeloooo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dvlab-research/SphereFormer] RuntimeError: CUDA error: out ofmemory (Issue #11)





 
Reopened #11.

**Comment by X-Lai** [comment]
Can you elaborate on that more concretely?

**Comment by pomeloooo** [comment]
I have found the cause of the problem. Due to the large dataset, I only used only one graphics card and there is not enough memory. It has been resolved so far. Thank you again for the author's reply




秋风扫落叶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dvlab-research/SphereFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dvlab-research/SphereFormer] RuntimeError: CUDA error: out of memory (Issue #11)





 
Can you elaborate on that more concretely?
