### ISSUE TITLE
About test result on SemanticKITTI

### ISSUE THREAD

**Issue by fengjiang5** [dvlab-research/SphereFormer#12]
Hello, 

Thanks for your great work!
I want to ask some questions about how the test result on SemanticKITTI dataset.
I use the code following to predict the label of test set. And I use **TTA** like your provided function `validation_tta`. I get result of 68.5 on the validation set, but the result has a big gap on the test set. By the way, I use the checkpoint provide in this repository. 
So could you please give some advice about how to improve the results on test set. Thanks a lot!
```
def test_tta(test_loader, model, criterion):
    if main_process():
        logger.info('>>>>>>>>>> Start Evaluation on test set >>>>>>>>>>')

    batch_time = AverageMeter()
    data_time = AverageMeter()
    
    with open('util/semantic-kitti.yaml', 'r') as stream:
        semkittiyaml = yaml.safe_load(stream)
    learning_map_inv = semkittiyaml['learning_map_inv']

    torch.cuda.empty_cache()

    loss_name = args.loss_name

    model.eval()
    end = time.time()
    for i, batch_data_list in enumerate(test_loader):

        data_time.update(time.time() - end)
    
        with torch.no_grad():
            output = 0.0
            for batch_data in batch_data_list:

                (coord, xyz, feat, target, offset, inds_reconstruct, file) = batch_data
                inds_reconstruct = inds_reconstruct.cuda(non_blocking=True)

                offset_ = offset.clone()
                offset_[1:] = offset_[1:] - offset_[:-1]
                batch = torch.cat([torch.tensor([ii]*o) for ii,o in enumerate(offset_)], 0).long()

                coord = torch.cat([batch.unsqueeze(-1), coord], -1)
                spatial_shape = np.clip((coord.max(0)[0][1:] + 1).numpy(), 128, None)
            
                coord, xyz, feat, target, offset = coord.cuda(non_blocking=True), xyz.cuda(non_blocking=True), feat.cuda(non_blocking=True), target.cuda(non_blocking=True), offset.cuda(non_blocking=True)
                batch = batch.cuda(non_blocking=True)

                sinput = spconv.SparseConvTensor(feat, coord.int(), spatial_shape, args.batch_size)

                assert batch.shape[0] == feat.shape[0]
                
                output_i = model(sinput, xyz, batch)
                output_i = F.softmax(output_i[inds_reconstruct, :], -1)
                
                output = output + output_i
            output = output / len(batch_data_list)

        output = output.max(1)[1]
        n = coord.size(0)

        batch_time.update(time.time() - end)
        end = time.time()
        if (i + 1) % args.print_freq == 0 and main_process():
            logger.info('Test: [{}/{}] '
                        'Data {data_time.val:.3f} ({data_time.avg:.3f}) '
                        'Batch {batch_time.val:.3f} ({batch_time.avg:.3f}) '.format(i + 1, len(test_loader),
                                                          data_time=data_time,
                                                          batch_time=batch_time))
        output = output.cpu().numpy().reshape(-1)
        output += 1  # transfer from [0, 18] to [1, 19]
        output = np.vectorize(learning_map_inv.__getitem__)(output).astype(np.uint32)
        predict_path = file.split('/sequences/', 1)[1]
        # print(predict_path)
        predict_path = 'test_predict_val/' + 'sequences/' +\
                        predict_path.replace('velodyne', 'labels').replace('labels',
                            'predictions')[:-3] + 'label'
        if os.path.exists(predict_path[:-13]):
            assert output.shape == target.cpu().numpy().shape
            output.tofile(predict_path)
        else:
            os.makedirs(predict_path[:-13])
            assert output.shape == target.cpu().numpy().shape
            output.tofile(predict_path)
    logger.info('<<<<<<<<<<<<<<<<< End Evaluation <<<<<<<<<<<<<<<<<')
    
    return 
```

**Comment by fengjiang5** [comment]
Hope for your early reply! Thanks again!

**Comment by X-Lai** [comment]
Thanks for your interest in our work. For the result on test benchmark, please refer to [Here](https://github.com/dvlab-research/SphereFormer/issues/1).

**Comment by fatemechangizian** [comment]
@fengjiang5 Could you please share the environment that you used, I mean the version of the dependencies?
I tried to create a dockerfile using all the versions stated in the readme but I am still getting different errors while running the train.py.
Thank you so much.

**Comment by X-Lai** [comment]
Hi, I have uploaded the `requirements.txt` file. Hope this can help you.

> @fengjiang5 Could you please share the environment that you used, I mean the version of the dependencies? I tried to create a dockerfile using all the versions stated in the readme but I am still getting different errors while running the train.py. Thank you so much.

**Comment by fatemechangizian** [comment]
Great thanks, I will try and let you know.

**Comment by fengjiang5** [comment]
> Great thanks, I will try and let you know.
Hello, I just follow the installation pipeline from README.md.
If you have any error, you can copy and paste them here.

**Comment by fengjiang5** [comment]
> Hi, I have uploaded the `requirements.txt` file. Hope this can help you.
> 
> > @fengjiang5 Could you please share the environment that you used, I mean the version of the dependencies? I tried to create a dockerfile using all the versions stated in the readme but I am still getting different errors while running the train.py. Thank you so much.

Hello, I just follow the installation pipeline from README.md.
If you have any error, you can copy and paste them here.
I wiil try my best to help you.

**Comment by fengjiang5** [comment]
> Thanks for your interest in our work. For the result on test benchmark, please refer to [Here](https://github.com/dvlab-research/SphereFormer/issues/1).

It is so hard to add test trick... 😭

**Comment by fatemechangizian** [comment]
I still haven't succeeded to make the code run.
I am using this docker file to create the env:
```
FROM nvidia/cuda:11.1.1-devel-ubuntu20.04

# Set Debian frontend to non interactive
ARG DEBIAN_FRONTEND=noninteractive

# Start from clean distro with proper Timezone
RUN apt-get update && apt-get dist-upgrade -y && apt-get autoremove \
    && apt-get install -y --no-install-recommends tzdata \
    && ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata


# General packages needed by the other build steps
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils debconf-utils bash lsb-release
RUN apt-get update && apt-get install -y --no-install-recommends git openssh-client ca-certificates gnupg curl wget file

# Python Python and python extensions
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    ninja-build \
    python3-dev \
    python3-matplotlib \
    python3-numpy \
    python3-packaging \
    python3-pandas \	
    python3-pip \
    python3-tk \
    python3-venv \
    sshfs \
    tcpreplay

# Set bash the default shell
SHELL ["/bin/bash", "-c"]

RUN pip3 install numpy
RUN pip3 install -U scikit-learn
RUN pip3 install configparser pandas tqdm
RUN pip3 install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install torch-scatter==2.0.9
RUN pip3 install torch-geometric==1.7.2
RUN pip3 install spconv-cu111==2.1.21
RUN pip3 install torch-sparse==0.6.12 cumm-cu111==0.2.8 torch-cluster==1.6.0
RUN pip3 install tensorboard==2.9.1 timm==0.5.4 termcolor==1.1.0 tensorboardX==2.5.1
RUN pip3 install google-auth==2.8.0 google-auth-oauthlib==0.4.6 google-pasta==0.2.0
RUN pip3 install PyYAML==6.0
RUN pip3 install scipy==1.7.3
RUN pip3 install pccm==0.3.4
RUN pip3 install ccimport==0.3.7
```
the I installed the sptr using 
`cd third_party/SparseTransformer && python setup.py install
`
but while trying to run the training module using 
`python train.py --config config/semantic_kitti/semantic_kitti_unet32_spherical_transformer.yaml
`
I am getting this error:
```
root@1a836b32a4e6:/home# python3 train.py --config config/semantic_kitti/semantic_kitti_unet32_spherical_transformer.yaml
Traceback (most recent call last):
  File "train.py", line 902, in <module>
    main()
  File "train.py", line 92, in main
    main_worker(args.train_gpu, args.ngpus_per_node, args)
  File "train.py", line 107, in main_worker
    from model.unet_spherical_transformer import Semantic as Model
  File "/home/model/unet_spherical_transformer.py", line 11, in <module>
    from model.spherical_transformer import SphereFormer
  File "/home/model/spherical_transformer.py", line 7, in <module>
    from third_party.SparseTransformer.sptr import to_3d_numpy, SparseTrTensor, sparse_self_attention, get_indices_params
  File "/home/third_party/SparseTransformer/sptr/__init__.py", line 2, in <module>
    from .utils import *
  File "/home/third_party/SparseTransformer/sptr/utils.py", line 5, in <module>
    from torch_geometric.nn import voxel_grid
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/usr/local/lib/python3.8/dist-packages/torch_sparse/__init__.py", line 15, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'
```
Could it be because of the python version?
Thanks for the help in advance.

**Comment by alprnbg** [comment]
> root@1a836b32a4e6:/home# python3 train.py --config config/semantic_kitti/semantic_kitti_unet32_spherical_transformer.yaml
> Traceback (most recent call last):
>   File "train.py", line 902, in <module>
>     main()
>   File "train.py", line 92, in main
>     main_worker(args.train_gpu, args.ngpus_per_node, args)
>   File "train.py", line 107, in main_worker
>     from model.unet_spherical_transformer import Semantic as Model
>   File "/home/model/unet_spherical_transformer.py", line 11, in <module>
>     from model.spherical_transformer import SphereFormer
>   File "/home/model/spherical_transformer.py", line 7, in <module>
>     from third_party.SparseTransformer.sptr import to_3d_numpy, SparseTrTensor, sparse_self_attention, get_indices_params
>   File "/home/third_party/SparseTransformer/sptr/__init__.py", line 2, in <module>
>     from .utils import *
>   File "/home/third_party/SparseTransformer/sptr/utils.py", line 5, in <module>
>     from torch_geometric.nn import voxel_grid
>   File "/usr/local/lib/python3.8/dist-packages/torch_geometric/__init__.py", line 5, in <module>
>     import torch_geometric.data
>   File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/__init__.py", line 1, in <module>
>     from .data import Data
>   File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/data.py", line 8, in <module>
>     from torch_sparse import coalesce, SparseTensor
>   File "/usr/local/lib/python3.8/dist-packages/torch_sparse/__init__.py", line 15, in <module>
>     torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
> AttributeError: 'NoneType' object has no attribute 'origin'

Hi @fatemechangizian. I got a similar error and could solve it by installing torch_scatter and torch_sparse by specifying the cuda version like below:

```
pip install torch_scatter==2.0.8 -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
pip install torch_sparse==0.6.12 -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
pip install torch_geometric==1.7.2 -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
pip install torch_cluster==1.5.9 -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
```
I also had to downgrade the version of torch_scatter from 2.0.9 to 2.0.8 since cu111 doesn't have the binaries for 2.0.9. 
Hope that helps.

**Comment by fatemechangizian** [comment]
@alprnbg Great, Thanks for the reply. I tested it now and it worked.
The only thing is that I wanted to also add the installation step of 'cd third_party/SparseTransformer && python setup.py install' in the docker but I was getting an error. May I know how you did that part?
I was doing it like this:
```
#RUN git clone https://github.com/dvlab-research/SphereFormer.git && \
#    cd SphereFormer/third_party/SparseTransformer && \
#    python3 setup.py install
```

**Comment by X-Lai** [comment]
Can you try `git clone https://github.com/dvlab-research/SphereFormer.git --recursive`? You should add the `--recursive` at the end of the command.

**Comment by alprnbg** [comment]
I used gcc 8.3 for the compilation of SparseTransformer since I was getting some errors with gcc > 10. Another thing which is weird is that you need to import torch_sparse before sptr_cuda, otherwise it throws an error which is libc10.so cannot be found.

**Comment by fatemechangizian** [comment]
Adding `--recursive `didn't resolve the issue. Here is the error
```
 > [24/24] RUN git clone https://github.com/dvlab-research/SphereFormer.git --recursive &&     cd SphereFormer/third_party/SparseTransformer &&     python3 setup.py install:
#0 0.313 Cloning into 'SphereFormer'...
#0 6.941 No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
#0 6.941 running install
#0 6.990 running bdist_egg
#0 6.990 running egg_info
#0 6.990 creating sptr.egg-info
#0 6.990 writing sptr.egg-info/PKG-INFO
#0 6.990 writing dependency_links to sptr.egg-info/dependency_links.txt
#0 6.990 writing top-level names to sptr.egg-info/top_level.txt
#0 6.991 writing manifest file 'sptr.egg-info/SOURCES.txt'
#0 7.021 reading manifest file 'sptr.egg-info/SOURCES.txt'
#0 7.022 writing manifest file 'sptr.egg-info/SOURCES.txt'
#0 7.022 installing library code to build/bdist.linux-x86_64/egg
#0 7.022 running install_lib
#0 7.022 running build_ext
#0 7.039 building 'sptr_cuda' extension
#0 7.039 creating /SphereFormer/third_party/SparseTransformer/build
#0 7.039 creating /SphereFormer/third_party/SparseTransformer/build/temp.linux-x86_64-3.8
#0 7.039 creating /SphereFormer/third_party/SparseTransformer/build/temp.linux-x86_64-3.8/src
#0 7.039 creating /SphereFormer/third_party/SparseTransformer/build/temp.linux-x86_64-3.8/src/sptr
#0 7.040 creating /SphereFormer/third_party/SparseTransformer/build/temp.linux-x86_64-3.8/src/sptr/attention
#0 7.040 creating /SphereFormer/third_party/SparseTransformer/build/temp.linux-x86_64-3.8/src/sptr/precompute
#0 7.040 creating /SphereFormer/third_party/SparseTransformer/build/temp.linux-x86_64-3.8/src/sptr/rpe
#0 7.041 Traceback (most recent call last):
#0 7.041   File "setup.py", line 12, in <module>
#0 7.041     setup(
#0 7.041   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
#0 7.041     return distutils.core.setup(**attrs)
#0 7.041   File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
#0 7.041     dist.run_commands()
#0 7.041   File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
#0 7.041     self.run_command(cmd)
#0 7.041   File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
#0 7.041     cmd_obj.run()
#0 7.041   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
#0 7.041     self.do_egg_install()
#0 7.041   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
#0 7.041     self.run_command('bdist_egg')
#0 7.041   File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
#0 7.041     self.distribution.run_command(command)
#0 7.041   File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
#0 7.041     cmd_obj.run()
#0 7.041   File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
#0 7.041     cmd = self.call_command('install_lib', warn_dir=0)
#0 7.041   File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
#0 7.041     self.run_command(cmdname)
#0 7.041   File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
#0 7.041     self.distribution.run_command(command)
#0 7.041   File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
#0 7.041     cmd_obj.run()
#0 7.041   File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
#0 7.041     self.build()
#0 7.041   File "/usr/lib/python3.8/distutils/command/install_lib.py", line 109, in build
#0 7.041     self.run_command('build_ext')
#0 7.041   File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
#0 7.041     self.distribution.run_command(command)
#0 7.041   File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
#0 7.041     cmd_obj.run()
#0 7.041   File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 87, in run
#0 7.041     _build_ext.run(self)
#0 7.041   File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
#0 7.041     self.build_extensions()
#0 7.041   File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
#0 7.041     build_ext.build_extensions(self)
#0 7.041   File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
#0 7.041     self._build_extensions_serial()
#0 7.041   File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
#0 7.041     self.build_extension(ext)
#0 7.041   File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 208, in build_extension
#0 7.041     _build_ext.build_extension(self, ext)
#0 7.041   File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
#0 7.041     objects = self.compiler.compile(sources,
#0 7.041   File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 524, in unix_wrap_ninja_compile
#0 7.041     cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
#0 7.041   File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 423, in unix_cuda_flags
#0 7.041     cflags + _get_cuda_arch_flags(cflags))
#0 7.041   File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1561, in _get_cuda_arch_flags
#0 7.041     arch_list[-1] += '+PTX'
#0 7.041 IndexError: list index out of range
```

**Comment by alprnbg** [comment]
I think you need to install cuda from source, as well. Pytorch comes with its own cuda runtime libraries but that's not enough for the compilation of SparseTransformer. You should be able to run nvcc to compile it.

**Comment by fatemechangizian** [comment]
I managed to build the docker by adding `DOCKER_BUILDKIT=0 docker build -t ....`

**Comment by completezealous** [comment]
> Hello,
> 
> Thanks for your great work! I want to ask some questions about how the test result on SemanticKITTI dataset. I use the code following to predict the label of test set. And I use **TTA** like your provided function `validation_tta`. I get result of 68.5 on the validation set, but the result has a big gap on the test set. By the way, I use the checkpoint provide in this repository. So could you please give some advice about how to improve the results on test set. Thanks a lot!
> 
> ```
> def test_tta(test_loader, model, criterion):
>     if main_process():
>         logger.info('>>>>>>>>>> Start Evaluation on test set >>>>>>>>>>')
> 
>     batch_time = AverageMeter()
>     data_time = AverageMeter()
>     
>     with open('util/semantic-kitti.yaml', 'r') as stream:
>         semkittiyaml = yaml.safe_load(stream)
>     learning_map_inv = semkittiyaml['learning_map_inv']
> 
>     torch.cuda.empty_cache()
> 
>     loss_name = args.loss_name
> 
>     model.eval()
>     end = time.time()
>     for i, batch_data_list in enumerate(test_loader):
> 
>         data_time.update(time.time() - end)
>     
>         with torch.no_grad():
>             output = 0.0
>             for batch_data in batch_data_list:
> 
>                 (coord, xyz, feat, target, offset, inds_reconstruct, file) = batch_data
>                 inds_reconstruct = inds_reconstruct.cuda(non_blocking=True)
> 
>                 offset_ = offset.clone()
>                 offset_[1:] = offset_[1:] - offset_[:-1]
>                 batch = torch.cat([torch.tensor([ii]*o) for ii,o in enumerate(offset_)], 0).long()
> 
>                 coord = torch.cat([batch.unsqueeze(-1), coord], -1)
>                 spatial_shape = np.clip((coord.max(0)[0][1:] + 1).numpy(), 128, None)
>             
>                 coord, xyz, feat, target, offset = coord.cuda(non_blocking=True), xyz.cuda(non_blocking=True), feat.cuda(non_blocking=True), target.cuda(non_blocking=True), offset.cuda(non_blocking=True)
>                 batch = batch.cuda(non_blocking=True)
> 
>                 sinput = spconv.SparseConvTensor(feat, coord.int(), spatial_shape, args.batch_size)
> 
>                 assert batch.shape[0] == feat.shape[0]
>                 
>                 output_i = model(sinput, xyz, batch)
>                 output_i = F.softmax(output_i[inds_reconstruct, :], -1)
>                 
>                 output = output + output_i
>             output = output / len(batch_data_list)
> 
>         output = output.max(1)[1]
>         n = coord.size(0)
> 
>         batch_time.update(time.time() - end)
>         end = time.time()
>         if (i + 1) % args.print_freq == 0 and main_process():
>             logger.info('Test: [{}/{}] '
>                         'Data {data_time.val:.3f} ({data_time.avg:.3f}) '
>                         'Batch {batch_time.val:.3f} ({batch_time.avg:.3f}) '.format(i + 1, len(test_loader),
>                                                           data_time=data_time,
>                                                           batch_time=batch_time))
>         output = output.cpu().numpy().reshape(-1)
>         output += 1  # transfer from [0, 18] to [1, 19]
>         output = np.vectorize(learning_map_inv.__getitem__)(output).astype(np.uint32)
>         predict_path = file.split('/sequences/', 1)[1]
>         # print(predict_path)
>         predict_path = 'test_predict_val/' + 'sequences/' +\
>                         predict_path.replace('velodyne', 'labels').replace('labels',
>                             'predictions')[:-3] + 'label'
>         if os.path.exists(predict_path[:-13]):
>             assert output.shape == target.cpu().numpy().shape
>             output.tofile(predict_path)
>         else:
>             os.makedirs(predict_path[:-13])
>             assert output.shape == target.cpu().numpy().shape
>             output.tofile(predict_path)
>     logger.info('<<<<<<<<<<<<<<<<< End Evaluation <<<<<<<<<<<<<<<<<')
>     
>     return 
> ```

Hello, can you provide more detailed code about semantickitti's test set to make predictions and save the prediction results? I used part of the code you provided now, but encountered the following problems：
![image](https://github.com/dvlab-research/SphereFormer/assets/56358219/535c39e4-9dc9-433c-9cec-c498e834ae92)
![image](https://github.com/dvlab-research/SphereFormer/assets/56358219/d1d29c72-42f2-4700-a282-bb64d8ad18fc)
Thanks a lot!
