### ISSUE TITLE
稀疏tensor特征转回到原tensor特征

### ISSUE THREAD

**Issue by Daybreak-Zheng** [dvlab-research/SphereFormer#13]
非常好的工作，请问如何将提取得到的稀疏tensor特征再转回到原tensor特征呢？ 

 期待您的回复！

**Comment by X-Lai** [comment]
你好，我不是很清楚您的问题，可以具体一些吗？

**Comment by Daybreak-Zheng** [comment]
How can I convert the SparseTensor from a model to DenseTensor? Can you give me an example?
Looking forward to your reply!

**Comment by X-Lai** [comment]
Do you mean `spconv.SparseConvTensor`? You can refer to the source code of `spconv`, which has already implemented the function to transform into a dense representation.
