### ISSUE TITLE
pretrain model can not be load correctly

### ISSUE THREAD

**Issue by zengziru** [dvlab-research/SphereFormer#15]
Hello! Thanks a lot for your inspiring work! Now I want to load your pretrain model of semantic-kitti to test the result. But it seems some errors from it like: size mismatch for module.unet.conv2.2.weight: copying a param with shape torch.size([2,2,2,64,32]) from checkpoint, the shape in current model is torch.size ([64,2,2,2,32])

**Comment by X-Lai** [comment]
I think this is caused by the inconsistency of `spconv` version. You can either change the version of `spconv`, or simply reshape the parameter.
