### ISSUE TITLE
Prediction result is very different with GT.

### ISSUE THREAD

**Issue by yuanhd17** [dvlab-research/SphereFormer#17]
Hello!
Thanks for your greate work. I have done visualization on semanticKITTI, left image is rendered by .lable which is GT, right image is rendered by the predict result from SphereFormer pre-trained model. There are large differences between them. Is it caused by pre-trained model or my test code has bug?
![image](https://user-images.githubusercontent.com/51024129/233069284-a4d81bee-4bc3-4add-ba84-928064df6319.png)

**Comment by lymdove** [comment]
![image](https://user-images.githubusercontent.com/51024129/233070783-30e790a8-9163-404f-b133-8f3652b6f171.png)

**Comment by yuanhd17** [comment]
> Hello! Thanks for your greate work. I have done visualization on semanticKITTI, left image is rendered by .lable which is GT, right image is rendered by the predict result from SphereFormer pre-trained model. There are large differences between them. Is it caused by pre-trained model or my test code has bug? ![image](https://user-images.githubusercontent.com/51024129/233069284-a4d81bee-4bc3-4add-ba84-928064df6319.png)

Thanks! I have solve this problem. SphereFormer ignores label==0, so it can give 19 labels not 20. Predict result add 1 goes right.
![9d1bb43d-79ce-48b7-9bb0-66bda594e2fd](https://user-images.githubusercontent.com/51024129/233095715-ef9027bf-8604-4c32-9e30-a12df1a26ea6.jpeg)

And i test it on my own dataset. Performs are so beautiful! Thanks! Your work helps a lot.

**Comment by X-Lai** [comment]
Sounds great.

**Comment by LurkerLuo** [comment]
> Hello! Thanks for your greate work. I have done visualization on semanticKITTI, left image is rendered by .lable which is GT, right image is rendered by the predict result from SphereFormer pre-trained model. There are large differences between them. Is it caused by pre-trained model or my test code has bug? ![image](https://user-images.githubusercontent.com/51024129/233069284-a4d81bee-4bc3-4add-ba84-928064df6319.png)

Hello, I am new to the semantic segmentation of 3D point clouds. I would like to hear from you about the results visualization work, can I get your contact information? My email is luoy1014116@gmail.com.

**Comment by illuosion** [comment]
Hi, I saw your visualization of the segmentation results and it was amazing! I would like to do some visualization of this piece as well, can you provide me with your test file? Thank you very much! My email is 1222014113@njupt.edu.cn

**Comment by dandon223** [comment]
I am doing something similar. 
You can use open3d for visualization.
Basically after you get output from model:
```
output = output.max(1)[1]
```
You create PointCloud class from open3d
```
pcl = o3d.geometry.PointCloud()
pcl.points = o3d.utility.Vector3dVector(points[:, :3])
pcl.colors = o3d.utility.Vector3dVector(np.array([colour_map[str(x + 1)] for x in output], dtype='float64'))
```
Where colour_map is basically map like this one (only with more key value pairs):
```
colour_map = {'0': [1.0, 1.0, 1.0], # ignore
                  '1': [0.0, 0.0, 0.0]}
```
To visualize this you use:
```
o3d.visualization.draw_geometries([pcl])
```

**Comment by guanba666** [comment]
@LurkerLuo  I encountered the same problem. May I ask where to add 1

**Comment by guanba666** [comment]
@lymdove I encountered the same problem. May I ask where to add 1
