### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by KSonPham** [dvlab-research/SphereFormer#19]
Hi guys, 

I tried to create a docker image to train this paper. However, i encountered this error and honestly don't know how to fix it. Would it be possible to share yours? 
![image](https://user-images.githubusercontent.com/57077087/233609515-a9f5f3d3-22f0-47b1-aaae-68fcfed24c7f.png)

Best regards,
Pham

**Comment by X-Lai** [comment]
Sorry about that, I used conda for this environment, so docker image is not available. It seems that installing `sptr` fails. Can you tell me which version of `gcc`, `g++` and `pytorch` is used?

**Comment by fatemechangizian** [comment]
@KSonPham 
Hello, I have the same problem running it inside docker, did you manage to make it work?
I have gcc and g++ version of 7.5.0 and torch version 1.8.0+cu111 and I am getting this error:
```
root@2d522099bc0b:/home# python3 train.py --config config/semantic_kitti/semantic_kitti_unet32_spherical_transformer.yaml
Traceback (most recent call last):
  File "train.py", line 902, in <module>
    main()
  File "train.py", line 92, in main
    main_worker(args.train_gpu, args.ngpus_per_node, args)
  File "train.py", line 107, in main_worker
    from model.unet_spherical_transformer import Semantic as Model
  File "/home/model/unet_spherical_transformer.py", line 11, in <module>
    from model.spherical_transformer import SphereFormer
  File "/home/model/spherical_transformer.py", line 7, in <module>
    from third_party.SparseTransformer.sptr import to_3d_numpy, SparseTrTensor, sparse_self_attention, get_indices_params
  File "/home/third_party/SparseTransformer/sptr/__init__.py", line 2, in <module>
    from .utils import *
  File "/home/third_party/SparseTransformer/sptr/utils.py", line 5, in <module>
    from torch_geometric.nn import voxel_grid
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/__init__.py", line 1, in <module>
    import torch_geometric.utils
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/utils/__init__.py", line 3, in <module>
    from .scatter import scatter
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/utils/scatter.py", line 7, in <module>
    import torch_geometric.typing
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/typing.py", line 37, in <module>
    import torch_sparse  # noqa
  File "/usr/local/lib/python3.8/dist-packages/torch_sparse/__init__.py", line 40, in <module>
    from .tensor import SparseTensor  # noqa
  File "/usr/local/lib/python3.8/dist-packages/torch_sparse/tensor.py", line 13, in <module>
    class SparseTensor(object):
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_script.py", line 974, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_script.py", line 67, in _compile_and_register_class
    torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError: 
Tried to access nonexistent attribute or method 'crow_indices' of type 'Tensor'.:
  File "/usr/local/lib/python3.8/dist-packages/torch_sparse/tensor.py", line 109
    def from_torch_sparse_csr_tensor(self, mat: torch.Tensor,
                                     has_value: bool = True):
        rowptr = mat.crow_indices()
                 ~~~~~~~~~~~~~~~~ <--- HERE
        col = mat.col_indices()
```

**Comment by KSonPham** [comment]
@X-Lai 
My error is very silly. if I ran python third_party/SparseTransformer/setup.py install, this error will occur. If it is python setup.py install, everything is fine. Hope that answered your question @fatemechangizian.

**Comment by fatemechangizian** [comment]
@KSonPham do you mind if you share the dockerfile you are using?

**Comment by KSonPham** [comment]
@fatemechangizian https://hub.docker.com/r/positivevibe/huggingface Dont worry about the name :dagger:

**Comment by KSonPham** [comment]
@X-Lai 
In the paper, you used distance = 100 for KITTI and 80 for nuScenes, but in the KITTI config file it is 80. Which one is correct then? Thank you
![image](https://user-images.githubusercontent.com/57077087/233933599-db2df854-b609-4626-98b7-59c1a3d2345b.png)

**Comment by fatemechangizian** [comment]
> @fatemechangizian https://hub.docker.com/r/positivevibe/huggingface Dont worry about the name dagger

Great thank you so much. I am still curious what was the problem with my dockerfile, do you mind if you can send me the dockerfile just to investigate the issue with mine? here is my email: f.changizian13@gmail.com or share it here.

**Comment by X-Lai** [comment]
> @X-Lai In the paper, you used distance = 100 for KITTI and 80 for nuScenes, but in the KITTI config file it is 80. Which one is correct then? Thank you ![image](https://user-images.githubusercontent.com/57077087/233933599-db2df854-b609-4626-98b7-59c1a3d2345b.png)

Thank you for pointing out this issue. There may be a typo in Sec. 4.1 (Implementation Details) of our paper. We mentioned that for SemanticKITTI, the window shape is set to [120, 2, 2], which should be [80, 2, 2] like in the yaml config. Also, one thing to note is that setting the window shape to [120, 2, 2] is actually equivalent to [80,2,2], since the maximum distance should be lower than 80m, so the partitions for both window shapes are all the same.

**Comment by KSonPham** [comment]
HI @X-Lai,
but why do you clip the lidar scan with the pc_range? And if you clip that to 51.2 does 80m windows shape still makes sense?

**Comment by X-Lai** [comment]
Clipping with a pc_range is used because the maximum number of voxels is limited by INT32_MAX in `spconv`. Even clipping with 51.2m, the window shape of [2,2,80] still makes sense since the partitions are equivalent as long as the window size is greater than sqrt(51.2\*51.2 + 4\*4).

**Comment by LIvanoff** [comment]
> > @fatemechangizian https://hub.docker.com/r/positivevibe/huggingface Dont worry about the name dagger
> 
> Great thank you so much. I am still curious what was the problem with my dockerfile, do you mind if you can send me the dockerfile just to investigate the issue with mine? here is my email: [f.changizian13@gmail.com](mailto:f.changizian13@gmail.com) or share it here.

Can you send the docker file?
