### ISSUE TITLE
The difference between the results of val and test

### ISSUE THREAD

**Issue by rogercomeon** [dvlab-research/SphereFormer#2]
Your work is excellent. I would like to ask if you directly use the given val weight for the test. It seems that the results of val and test are a bit different, and the result of val does not seem to exceed 2DPASS.

**Comment by X-Lai** [comment]
Thanks for your interest in our work. 

The testing results are also trained on the additional validation set, so their models are different from the given val weights. Besides, for testing, we also utilize commonly used tricks such as gt instance sampling and testing-time augmentation.

For comparison with 2DPASS, we do not strictly follow their experimental settings (e.g., voxel size, training iterations, learning rate, optimizer, scheduler, extra 2D data, model architecture, etc.), which causes the inconsistency. For an informal comparison, it seems that our approach is slightly better in terms of single-forward performance on nuScenes val set. But ours are slightly inferior to 2DPASS on SemanticKITTI val set.

**Comment by rogercomeon** [comment]
Thank you, I'm great to see such wonderful work

**Comment by rogercomeon** [comment]
Can you tell me the version of the spcnv library, I have the following error when I use the spconv==2.3.3 installed by pip by default
ImportError: arg(): could not convert default argument 'workspace: tv::Tensor' in method '<class 'spconv.core_cc.csrc.sparse.convops.gemmops.GemmTunerSimple'>.run_with_tuned_result' into a Python object (type not registered yet?)

**Comment by X-Lai** [comment]
Sorry for the confusion. The version for `spconv` is 2.1.21.

**Comment by rogercomeon** [comment]
Thank you very much for your reply, but after I installed spconv version 2.1.21, the following errors appeared again：
ImportError: cannot import name 'TensorOpParams' from 'cumm.gemm.algospec.core' (/home/lj/miniconda3/envs/spformer/lib/python3.7/site-packages/cumm/gemm/algospec/core.py)
Could you please tell me your cumm version?
