### ISSUE TITLE
A question about the validation results

### ISSUE THREAD

**Issue by ideasplus** [dvlab-research/SphereFormer#20]
Hi,

Thanks for your open-sourced code. 

I have trained two models on SemanticKITTI using your provided default config. After training, I get the following results.
the first try: `Best Iou: 0.664`
the second try: `Best Iou: 0.666`

The val mIoU I got is lower than your reported value (67.8) in README page. Is the performance difference normal?  Can I use the result (66.6) in my research (not about improving performance on semantic segmentation task)?

**Comment by X-Lai** [comment]
The performance does fluctuate sometimes. But I think the difference results should be within 1.0% mIoU. The reproduced results differ somehow too much. Does anything including config or GPU type or environment (e.g., versions of PyTorch / CUDA) keep all the same?

**Comment by ideasplus** [comment]
Hi, I use 4 Tesla V100 to train the model and your provided instructions to create the conda environment.

**Comment by X-Lai** [comment]
I see. I think that you can use the reproduced results as long as a fair comparison is made.

**Comment by ideasplus** [comment]
Thanks for your suggestion!
