### ISSUE TITLE
typeerror

### ISSUE THREAD

**Issue by rsleishaui** [dvlab-research/SphereFormer#21]
Hello, I encountered the following error when reproducing the training code, and I don't quite understand what's going on.

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/root/anaconda3/envs/ST/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/data/SphereFormer/train.py", line 410, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, criterion, optimizer, epoch, scaler, scheduler, gpu)
  File "/data/SphereFormer/train.py", line 579, in train
    allAcc = sum(intersection_meter.sum) / (sum(target_meter.sum) + 1e-10)
TypeError: 'int' object is not iterable

**Comment by X-Lai** [comment]
This error may be caused by an incorrect data root. You may check whether the data path follows the instructions in the README file.

**Comment by completezealous** [comment]
> Hello, I encountered the following error when reproducing the training code, and I don't quite understand what's going on.
> 
> -- Process 3 terminated with the following error: Traceback (most recent call last): File "/root/anaconda3/envs/ST/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap fn(i, *args) File "/data/SphereFormer/train.py", line 410, in main_worker loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, criterion, optimizer, epoch, scaler, scheduler, gpu) File "/data/SphereFormer/train.py", line 579, in train allAcc = sum(intersection_meter.sum) / (sum(target_meter.sum) + 1e-10) TypeError: 'int' object is not iterable



> Hello, I encountered the following error when reproducing the training code, and I don't quite understand what's going on.
> 
> -- Process 3 terminated with the following error: Traceback (most recent call last): File "/root/anaconda3/envs/ST/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap fn(i, *args) File "/data/SphereFormer/train.py", line 410, in main_worker loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, criterion, optimizer, epoch, scaler, scheduler, gpu) File "/data/SphereFormer/train.py", line 579, in train allAcc = sum(intersection_meter.sum) / (sum(target_meter.sum) + 1e-10) TypeError: 'int' object is not iterable

I had the same problem as you. How did you solve it?
