### ISSUE TITLE
How many hours to train on the SemanticKITTI

### ISSUE THREAD

**Issue by HaoRan-hash** [dvlab-research/SphereFormer#22]
I run the code, and observe that an epoch takes 2 hours.
So, the whole training process (50 epochs) takes about 100 hours (4 days).
Does it take so long to train ?

Note: I use four 2080ti.

**Comment by X-Lai** [comment]
Normally, it takes about 50 hours to train on 4 RTX3090 GPUs. I think the slow training speed is caused by the CPU you used.

**Comment by KSonPham** [comment]
Hi @X-Lai,

where do you think could be the bottleneck?

**Comment by X-Lai** [comment]
It depends on your hardware. If you run with RTX3090 or 2080Ti but needs much more than 50 hours, I think the bottleneck may be the CPU for data IO / processing.  But if you only need roughly 50 hours, then the bottleneck should be the backward operation of self-attention. We have already done a lot of acceleration for forward inference of self-attention and achieved a good inference speed. But the backward operation is somehow unfriendly for hardware optimization, so it still needs improving for training.
