### ISSUE TITLE
test 128 lines result is not performance well on semantic kitti?

### ISSUE THREAD

**Issue by yufeng89** [dvlab-research/SphereFormer#26]
hi，I‘m a researcher in point cloud semantic segmantation.your work is excelent.
when I test 128 lines with my point cloud data using your released semantic-kitti  pretrained model,the result is not performance well.could you help analysis it? thanks.
ps:could U share your waymo petrained model,just for a reasearch. Thanks.
email:1293492375@qq.com
Thanks!

**Comment by X-Lai** [comment]
Hi, what do you mean by "128 lines"? Do you mean the beam lines of the LiDAR sensor is 128-line?

Both SemanticKITTI and Waymo scenes are 64-line, so the pre-trained weights on these two datasets cannot directly work well on 128-line LiDAR scenes.

**Comment by yufeng89** [comment]
yes,the beam lines of the LiDAR sensor is 128-line.is there a good to solve the problem of 128-line segmentation？i donot have 128-line datasets.
could U kindly provide waymo pretrained model for test?appreciate it!

**Comment by X-Lai** [comment]
It is a domain adaptation problem. You may refer to related publications. The waymo model has been sent.

**Comment by rockywind** [comment]
Hi, can you sent me a waymo model?
My e-mail is: rockywin.wang@zongmutech.com.
The waymo dataset's number is below.
Can you provide the size of converted waymo dataset?
![image](https://github.com/dvlab-research/SphereFormer/assets/14838781/48318525-c813-4f81-b4ec-2b5d7f20ade2)

**Comment by fatemechangizian** [comment]
> yes,the beam lines of the LiDAR sensor is 128-line.is there a good to solve the problem of 128-line segmentation？i donot have 128-line datasets. could U kindly provide waymo pretrained model for test?appreciate it!

@X-Lai @yufeng89 Hello, Is it possible for you to share the pre-trained weights with me, please, I would like to have a model trained on 128 lines lidar.
Here is my email: f.changizian13@gmail.com
Thank you so much in advance.

**Comment by KeanuWongves** [comment]
@X-Lai  @yufeng89 @fatemechangizian  Hi, guys, I also have my own dataset with 128-line lidar sensor, could you plz share pretrained waymo weight with me? Thx a lot.
email: wcyjerry@qq.com

**Comment by bigliuyq** [comment]
@X-Lai @yufeng89 @fatemechangizian @wcyjerry @rockywind 
Hi, guys, could you plz share pretrained waymo weight with me? I would like to test on my own dataset with 128-line lidar sensor,  Thx a lot.
email: 864367873@qq.com
