### ISSUE TITLE
Problem while downloading torch

### ISSUE THREAD

**Issue by swapnik-iitkgp** [dvlab-research/SphereFormer#29]
hello there, I am facing a problem while downloading torch using the given command, i.e. it is showing me this version is not found in the given link. So, can you please provide an alternative for this....

**Comment by X-Lai** [comment]
This command is directly copied from pytorch official website.

**Comment by L-Reichardt** [comment]
A little late for this answer, but I suspect is most likely a PyTorch / Python version mismatch issue in a virtual environment.

I tested pip-installation successfully with Python 3.8.10 and PyTorch 1.8 works fine. However e.g. Anaconda environments currently default to Python 3.11.4, where this link does not work.
During Anaconda environment creation, the Python version can be specified through  $ `conda create -n sphereformer python=3.8.10`

**Comment by X-Lai** [comment]
Thanks for your suggestion.
