### ISSUE TITLE
Size mismatch during SemanticKITTI Validation

### ISSUE THREAD

**Issue by jacoblambert** [dvlab-research/SphereFormer#35]
Hey guys, thanks for sharing your amazing work.

I'm just trying it out but have been met with this error:

```
[Exception|implicit_gemm_pair]indices=torch.Size([720506, 4]),bs=8,ss=[2048, 2048, 129],algo=ConvAlgo.MaskImplicitGemm,ksize=[3, 3, 3],stride=[1, 1, 1],padding=[1, 1, 1],dilation=[1, 1, 1],subm=True,transpose=False
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):
  File "train.py", line 902, in <module>
    main()
  File "train.py", line 92, in main
    main_worker(args.train_gpu, args.ngpus_per_node, args)
  File "train.py", line 410, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, criterion, optimizer, epoch, scaler, scheduler, gpu)
  File "train.py", line 498, in train
    output = model(sinput, xyz, batch)
  File "/home/pe/anaconda3/envs/sphereformer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pe/anaconda3/envs/sphereformer/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/pe/anaconda3/envs/sphereformer/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/pe/anaconda3/envs/sphereformer/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/pe/anaconda3/envs/sphereformer/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/pe/anaconda3/envs/sphereformer/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/pe/anaconda3/envs/sphereformer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pe/SphereFormer/model/unet_spherical_transformer.py", line 285, in forward
    output = self.unet(output, xyz, batch)
  File "/home/pe/anaconda3/envs/sphereformer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pe/SphereFormer/model/unet_spherical_transformer.py", line 174, in forward
    assert (inp.indices[:, 0] == batch).all()
RuntimeError: The size of tensor a (720506) must match the size of tensor b (360253) at non-singleton dimension 0
```

This occurs both training and validation SemanticKITTI (I made separate config files for each based on your guidelines). I also installed according to your Readme.

```
spconv-cu114              2.1.21                   pypi_0    pypi
sptr                      0.0.0                    pypi_0    pypi
tensorboard               2.11.2                   pypi_0    pypi
timm                      0.9.2                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torch                     1.8.0+cu111              pypi_0    pypi
torch-cluster             1.5.9                    pypi_0    pypi
torch-geometric           1.7.2                    pypi_0    pypi
torch-scatter             2.0.9                    pypi_0    pypi
torch-sparse              0.6.12                   pypi_0    pypi
torchaudio                0.8.0                    pypi_0    pypi
torchvision               0.9.0+cu111              pypi_0    pypi
```

I tried with single GPU and two GPUs (2x 2080Ti) and changing the param in the config but same error.

Any ideas? May be related to #34 but it was closed without comment. I however notice that my tensor sizes are always mismatch by a factor of 2, which is different than #34. 

Thanks!

**Comment by jacoblambert** [comment]
In a different PC, I could get it to work. I set up the environment the same way, but there are some underlying differences that might be responsible for it: 

The failing PC has a 2080Ti in Ubuntu 20 with Cuda 11.6.
The working PC has an A6000 in Ubuntu 22 with Cuda 11.7.

**Comment by X-Lai** [comment]
I think the reason of this exception may be that the batch size for a single GPU is too large to make it successfully run by `spconv`. It is because the spatial shape for a point cloud is [batch_size, H, W, Z]. If the batch size is too large, then the product of `batch_size*H*W*Z` will be over INT32_MAX, this will cause the overflow issue inside `spconv`.

Can you try to lower the batch size per GPU to 1 or 2?

**Comment by jacoblambert** [comment]
Thanks for your response. I think even at batch_size=1 I get this error with a 3090.

The A6000 can train it. Actually, I found the memory usage for batch_size=1 hovers around 7 GB but occasionally spikes to 21GB and sometimes even 40GB. These are very brief so I'm wondering if there are some threads or processes that might be briefly overlapping because previous memory is cleared. Do you have any idea where these spikes might be coming from?

**Comment by brahami14** [comment]
Hello, 
i got this issue of mismatch  sizes whene i want to evaluate the pretrained model loaded on valid kitti dataset, have you any idea what is the problem ,  thanks in advance 
![image](https://github.com/dvlab-research/SphereFormer/assets/103207573/969fe02d-1136-4b64-8331-b334fc7c6e1d)

**Comment by jacoblambert** [comment]
@brahami14 For me this was only fixed by using a GPU with more memory.

Sorry for leaving this open so long.

**Comment by jayerone** [comment]
> Hello, i got this issue of mismatch sizes whene i want to evaluate the pretrained model loaded on valid kitti dataset, have you any idea what is the problem , thanks in advance ![image](https://github.com/dvlab-research/SphereFormer/assets/103207573/969fe02d-1136-4b64-8331-b334fc7c6e1d)

hello，I want to know how you solved this problem.

**Comment by jacoblambert** [comment]
> > Hello, i got this issue of mismatch sizes whene i want to evaluate the pretrained model loaded on valid kitti dataset, have you any idea what is the problem , thanks in advance ![image](https://github.com/dvlab-research/SphereFormer/assets/103207573/969fe02d-1136-4b64-8331-b334fc7c6e1d)
> 
> hello，I want to know how you solved this problem.

use bigger GPU :)
