### ISSUE TITLE
Voxel generate in seg and det?

### ISSUE THREAD

**Issue by huixiancheng** [dvlab-research/SphereFormer#36]
Hi, I want to know why do you use the [customize voxel gengerate methods](https://github.com/dvlab-research/SphereFormer/blob/0ff1e0ae84a4280fbecc9cfc3ac3aec41d24eeba/util/data_util.py#L91-L127) in segmentation tasks instead of `PointToVoxel` in [spconv](https://github.com/traveller59/spconv/blob/master/example/voxel_gen.py)?
Also, if i need to train both det&seg taskes, how do i gather voxel_seg_label or gather point-wise features from sematic segmentation result? Thx for any kind help.

**Comment by X-Lai** [comment]
This implementation follows some previous works, like Stratified Transformer and Point Transformer.

To get the point-wise features from the voxels, you need to use the inverse index map (e.g., `idx_recon`). The current implementation does not save it during training. We save it only during inference. So you need to modify the implementation.

**Comment by huixiancheng** [comment]
Thx for your kind reply.
