### ISSUE TITLE
3D detection

### ISSUE THREAD

**Issue by DezeZhao** [dvlab-research/SphereFormer#4]
hi, it is an excellent work. Could you please share your 3D detection code based on OpenPCDet? thank you.

**Comment by X-Lai** [comment]
Thanks for your interest in our work. I am currently preparing for the release. Please stay tuned and we will make it available soon.

**Comment by DezeZhao** [comment]
`    idx = idx + ((3*(2**(idx//2)) - 2)*a <= rel_pos_abs).float()
    idx = idx * (2*flag_float - 1) + (flag_float - 1)`

**Comment by DezeZhao** [comment]
> ` idx = idx + ((3*(2**(idx//2)) - 2)*a <= rel_pos_abs).float() 
idx = idx * (2*flag_float - 1) + (flag_float - 1)`

hello, I have difficulty in understanding these 2 lines. Could you please help me? thank you.

**Comment by DezeZhao** [comment]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/44592986/227995590-5c39c296-abd6-44cf-89cc-f86aa056df2d.png">

idx = 2 * torch.floor(torch.log((rel_pos_abs+2*a) / a) / np.log(2)) - 2 
idx = idx + ((3*(2**(idx//2)) - 2)*a <= rel_pos_abs).float()
 for these 2 lines codes of exponential splitting, I make above prove. Could you think it right? thank you.

**Comment by DezeZhao** [comment]
> <img alt="image" width="847" src="https://user-images.githubusercontent.com/44592986/227995590-5c39c296-abd6-44cf-89cc-f86aa056df2d.png">
> 
> idx = 2 * torch.floor(torch.log((rel_pos_abs+2_a) / a) / np.log(2)) - 2 idx = idx + ((3_(2**(idx//2)) - 2)*a <= rel_pos_abs).float() for these 2 lines codes of exponential splitting, I make above prove. Could you think it right? thank you.

@X-Lai thank you.

**Comment by X-Lai** [comment]
Yes, you're right. Actually, it implements the `exponential splitting` elaborated in our paper. The `a` means the initial split length. The following table is an example for the mapping function from `rel` to `idx`.

| rel | idx |
|---------------|:----:|
| ... | ... |
| [-2a, a) | -2 |
| [-a, 0) | -1 |
| [0, a) | 0 |
| [a, 2a) | 1 |
| [2a, 4a) | 2 |
| [4a, 6a) | 3 |
| [6a, 10a) | 4 |
| [10a, 14a) | 5 |
| ... | ... |

Starting from 0, the split length will double once used twice.

**Comment by DezeZhao** [comment]
hi @X-Lai ! could you please open source of detection code?

**Comment by X-Lai** [comment]
Sure, it should be released in late April.

**Comment by DezeZhao** [comment]
OK. Excited to look forward it!

**Comment by DezeZhao** [comment]
Hi @X-Lai, Could you please share your code for detection?

**Comment by zhaowenZhou** [comment]
Hi, @X-Lai, could you share your detection code pls? Thank you

**Comment by X-Lai** [comment]
@DezeZhao  @zhaowenZhou  Hi, the detection code is released now. Note that I have refactored the codebase, and haven't tested the performance. If everything works well, the detection performance on nuscenes val set should be around 63.2 mAP and 68.78 NDS. If you are in urgent need for the code, you can try first. If there is any problem, feel free to post issues. I will finish the testing in the following few days.

**Comment by DezeZhao** [comment]
Thank you!
