### ISSUE TITLE
Fails to load pretrained model

### ISSUE THREAD

**Issue by brahami14** [dvlab-research/SphereFormer#45]
Hello, anyone have any idea how to solve this problem
is it  due to the version of spconv because i am using spconv 2.x ?

thanks in advance 

![image](https://github.com/dvlab-research/SphereFormer/assets/103207573/e5919d98-ba23-4f00-a300-29d668a6719f)

**Comment by X-Lai** [comment]
Can you change another version of `spconv 2.x`?

**Comment by brahami14** [comment]
thank you so much for your answer @X-Lai

**Comment by brahami14** [comment]
@X-Lai   I have another question please why did you choose different voxel size for semantic kitti and nuscenes ?

**Comment by X-Lai** [comment]
Their sparsities are totally different. SemanticKITTI scenes scanned by 64-line LiDAR, while nuscenes scenes are by 32-line LiDAR.

**Comment by ParimiHarsha** [comment]
> thank you so much for your answer @X-Lai

I am facing the same issue, which version of spconv did you end up using?
Thanks in advance
