### ISSUE TITLE
Supplementary material about the paper

### ISSUE THREAD

**Issue by completezealous** [dvlab-research/SphereFormer#53]
Thank you very much for your open source code. You mentioned in your paper that there are detailed network architecture in the supplementary materials, but there are no supplementary materials at the end of the paper. Could you provide them if it is convenient.

**Comment by ygcchen** [comment]
Thanks to the author for making the project open source. Can you provide supplementary materials?

**Comment by X-Lai** [comment]
Here it is: https://openaccess.thecvf.com/content/CVPR2023/supplemental/Lai_Spherical_Transformer_for_CVPR_2023_supplemental.pdf.
