### ISSUE TITLE
The "pc_range" of the Semantickitti

### ISSUE THREAD

**Issue by ytrhhiaya** [dvlab-research/SphereFormer#58]
I see while data preprocessing,the point cloud are limit to the range[[-51.2, -51.2, -4]. [51.2, 51.2, 2.4]]. when I test the model in the testset(codalab), need I remove the point cloud range limitations？

**Comment by X-Lai** [comment]
No need to remove it. Actually, the points outside this range are very few. They won't change the final performance too much.
