### ISSUE TITLE
Missing requirements for train.py

### ISSUE THREAD

**Issue by airalcorn2** [dvlab-research/SphereFormer#7]
It looks like you need to do:

```bash
pip3 install torch_sparse==0.6.12 cumm-cu114==0.2.8 torch_cluster==1.5.9
```

before running:

```bash
python3 train.py
```

Version 0.6.12 of PyTorch Sparse is necessary to avoid the issue [here](https://github.com/rusty1s/pytorch_sparse/issues/207). Version 0.2.8 of `cumm` is necessary to avoid the issue [here](https://github.com/traveller59/spconv/issues/438).

**Comment by X-Lai** [comment]
Thank you for pointing out this issue. I will fix it.
