### ISSUE TITLE
exponential splitting code

### ISSUE THREAD

**Issue by DezeZhao** [dvlab-research/SphereFormer#8]
![image](https://user-images.githubusercontent.com/44592986/228120460-5104bf50-3a45-4bd0-8971-640a9915796b.png)

> idx = 2 * torch.floor(torch.log((rel_pos_abs+2_a) / a) / np.log(2)) - 2 idx = idx + ((3_(2**(idx//2)) - 2)*a <= rel_pos_abs).float() for these 2 lines codes of exponential splitting, I make above prove. Could you think it right? thank you.

@X-Lai thank you.

_Originally posted by @DezeZhao in https://github.com/dvlab-research/SphereFormer/issues/4#issuecomment-1485397594_

**Comment by X-Lai** [comment]
Yes, you're right. Actually, it implements the `exponential splitting` elaborated in our paper. The `a` means the initial split length. The following table is an example for the mapping function from `rel` to `idx`.

| rel | idx |
|---------------|:----:|
| ... | ... |
| [-2a, a) | -2 |
| [-a, 0) | -1 |
| [0, a) | 0 |
| [a, 2a) | 1 |
| [2a, 4a) | 2 |
| [4a, 6a) | 3 |
| [6a, 10a) | 4 |
| [10a, 14a) | 5 |
| ... | ... |

Starting from 0, the split length will double once used twice.

**Comment by DezeZhao** [comment]
Oh yeah. I get it now. Thank you. Because I got confused while reading code about it, which is different from your elabration in paper. Maybe above description is in supplementary material？ You may not provide supplementary materials in paper now. 
<img width="562" alt="image" src="https://user-images.githubusercontent.com/44592986/228126569-9d5c709a-9e77-4d50-98ca-421f988547ba.png">
