### ISSUE TITLE
More 3D Detection Results

### ISSUE THREAD

**Issue by ldkong1205** [dvlab-research/SphereFormer#9]
Hi @X-Lai, thanks for open-sourcing your work!

I noticed from your paper that you only conducted 3D object detection experiments on nuScenes. I would like to ask whether you have plans to test your SphereFormer on other mainstream 3D detection datasets, such as KITTI and Waymo Open. Thanks.

**Comment by X-Lai** [comment]
Thank you for your interest in our work. For object detection, we only conduct experiments on nuScenes for verification. But it will be easy to be extended to other datasets. When the codes for detection are released, you can try it yourself.

**Comment by ldkong1205** [comment]
Thanks for your information and looking forward to the code
